<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>		
		<RootNamespace>Microsoft.eShopWeb.Infrastructure</RootNamespace>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ApplicationCore\ApplicationCore.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Data\Migrations\" />
		<Compile Remove="Data\Queries\BasketQueryService.cs" />
	</ItemGroup>
</Project>
